name: FSR
version: 1.2.1
date: 2018-06-08
description: |
    FSR - Feedback Shift Register Package

authors:
    - name: Nusa Zidaric
      url: http://comsec.uwaterloo.ca/
    - name: Mark Aagaard
      url: http://comsec.uwaterloo.ca/
    - name: Guang Gong
      url: http://comsec.uwaterloo.ca/

GAP: "4.7"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://nzidaric.github.io/FSR
readme: README.md
packageinfo: https://nzidaric.github.io/FSR/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nzidaric/FSR/releases/download/v1.2.1/FSR-1.2.1.tar.gz

abstract: |

status: other
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    package FSR, LFSR, finite fields, sequences.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>ZAG18</span>]   <b class='BibAuthor'>Zidaric, N., Aagaard, M. and Gong, G.</b>,
     <i class='BibTitle'>FSR, FSR - Feedback Shift Register Package,
             Version 1.2.1</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://nzidaric.github.io/FSR">https://nzidaric.github.io/FSR</a></span>.
    </p>
    

bibtex: |
    @misc{ FSR1.2.1,
      author =           {Zidaric, N. and Aagaard, M. and Gong, G.},
      title =            {{FSR},   FSR   -   Feedback  Shift  Register  Package,
                          {V}ersion 1.2.1},
      month =            {Jun},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href                 {https://nzidaric.github.io/FSR}
                          {\texttt{https://nzidaric.github.io/}\discretionary
                          {}{}{}\texttt{FSR}}},
      keywords =         {package FSR; LFSR; finite fields; sequences},
      printedkey =       {ZAG18}
    }

